
<div class="text-light">

</div>

<div class="container">
 
  <div class="center">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
  
    <div class="carousel-item active">
      <img class="d-block w-100 img-index" src="/Midia/<?=$this->view->todos_quadrinhos[0]['id_usuario']?>/Quadrinhos/<?=$this->view->todos_quadrinhos[0]['titulo']?>/<?=$this->view->todos_quadrinhos[0]['capa']?>" alt="First slide">
    </div>
    <?php ?>
    <div class="carousel-item">
      <img class="d-block w-100 img-index" src="/Midia/<?=$this->view->todos_quadrinhos[1]['id_usuario']?>/Quadrinhos/<?=$this->view->todos_quadrinhos[1]['titulo']?>/<?=$this->view->todos_quadrinhos[1]['capa']?>"  alt="Second slide">
    </div>
   
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  
  </div>

</div>

<div class="bg-light p-4">

<div class="row container">
<div class="center">

</div>
<div class="col-md-9"><h4 class="">Quadrinhos</h4>
<h1> <?php //echo $this->View->todos_quadrinhos;
   // print_r($this->view->todos_quadrinhos);
?></h1>
 <div class="row p-2">
 <?php foreach($this->view->todos_quadrinhos as $key => $value){  $local = $value['id_usuario']; ?>
   <div class="col-md-3 ">
     <img class="imagem-tops" src="/Midia/<?=$local?>/Quadrinhos/<?=$value['titulo']?>/<?=$value['capa']?>">
     <h4><a href="\apresentacao_capitulo?qd=<?=$value['id']?>"><?= $value['titulo']?></a></h4>
     <p><?= $value['descricao']?></p>
     <p align="right"> by - <a href="pagina_autor?autor=<?=$local?>"><?= $value['autor']?></a> </p>
   </div>
   <?php } ?>
 </div>
 <h4>Artes:</h4>
 <div class="col-nd-3 row">
 <?php foreach($this->view->recupera_todas_artes as $key => $value){  $local = $value['id_usuario']; ?>
 <div class="col-md-3 ">
     <img class="imagem-tops" src="Midia/<?= $local?>/Artes/<?= $value['img']?>">
     <h4><a href="/capitulo?arte=<?=$value['id']?>&us=<?=$value['id_usuario']?>"><?=$value['titulo']?></a></h4>
     <p><?= $value['descricao']?></p>
     <p align="right"> by - <a href="/pagina_autor?autor=<?=$value['id_usuario']?>"><?= $value['autor']?></a> </p>
   </div>
  <?php } ?>
 </div>
</div>
<div class="col-md-3 p-3">
  <div class="btn btn-success">Ver Lista Completa </div>
  <h4>Tops :</h4>
  <ul class="list-group p-2">
   <li class="list-group-item"><a href="">Conto dos Gatos</a></li>
   <li class="list-group-item"><a href="">Conto de Denis</a></li>
   <li class="list-group-item"><a href="">Namco Blazer</a></li>
   
  </ul>
  <h4>One-shoots</h4>
  <ul class="list-group p-2">
   <li class="list-group-item"><a href="">Conto dos Gatos</a></li>
   <li class="list-group-item"><a href="">Conto de Denis</a></li>
   <li class="list-group-item"><a href="">Namco Blazer</a></li>
   
  </ul>
<div>
</div>

</div>
