
<div class="container p-5 mt-3" style="border: 2px solid yellow">
    <div class="center">
        <form class="form text-light" method="post" action="/autenticar">
            <label for="">Email</label>
            <input class="form-control" name="email" type="text">
            <label for="">Senha</label>
            <input class="form-control" name="senha" type="password">
            <input type="submit" class="btn btn-danger text-warning mt-3" value="Logar">
        </form>
        <a href="\registrar" class="text-warning">Não tem conta? Registre-se agora mesmo</a>
    </div>
</div>
