
<div class="container p-5 mt-3" style="border: 2px solid yellow">
    <div class="center">
        <form class="form text-light" method="post" action="\cadastrando">
            <label for="">Nome</label>
            <input class="form-control" type="text" name="nome">
            <label for="">Sobrenome</label>
            <input class="form-control" type="text" name="sobrenome">
            <label for="">NickName</label>
            <input class="form-control" type="text" name="nick">
            <label for="">Email</label>
            <input class="form-control" type="email" name="email">
            <label for="">Senha</label>
            <input class="form-control" type="password" name="senha">
            <input type="submit" class="btn btn-danger text-warning mt-3" name="registrar" value="Cadastrar">
        </form>
        <a href="\login" class="text-warning">Já tem conta? clique aqui para fazer login</a>
    </div>
</div>
