<div class="mt-4">
  <div class="container bg-light">
     <div class="center">
        <h3>Cadastrar Arte</h3>
        <form action="\nova_arte_cadastrada" class="form" method="post"  enctype="multipart/form-data" >
           <label for="">Titulo</label>
           <input class="form-control" name="titulo" type="text">
           <label for="">Descrição</label>
           <input class="form-control" type="text" name="descricao">
            <label for="">Arte</label>
            <input type="file" name="arte" onchange="previewImagem()"><br>
            <img id="img-arte" style="width: 300px; height: 300px;"><br><br>
            <input type="submit" class="btn btn-danger text-warning form-control" name="cadastrar">
        </form>
     </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
			function previewImagem(){
				var imagem = document.querySelector('input[name=arte]').files[0];
				var preview = document.querySelector("#img-arte");
				
				var reader = new FileReader();
				
				reader.onloadend = function () {
					preview.src = reader.result;
				}
				
				if(imagem){
					reader.readAsDataURL(imagem);
				}else{
					preview.src = "";
				}
			}
		</script>
       